default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER') { 'postgresql' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'aircall_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'aircall_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'aircall' } %>
